import pandas as pd
archivo=pd.read_excel("BI_Clientes.xlsx")
cliente=pd.DataFrame(archivo)

def YearlyIncome():
    print("====================================")
    print("calcular la media de YearlyIncome")
    media = cliente.YearlyIncome.mean()
    print(media)
    print("------------------------------------")
    print("Calcular la mediana de YearlyIncome")
    mediana = cliente.YearlyIncome.median()
    print(mediana)
    print("------------------------------------")
    print("Calcular la moda de YearlyIncome")
    moda = cliente.YearlyIncome.mode()
    print(moda)
    print("\n")
YearlyIncome()

def TotalChildren():
    print("====================================")
    print("calcular la media de TotalChildren")
    media = cliente.TotalChildren.mean()
    print(media)
    print("------------------------------------")
    print("Calcular la mediana de TotalChildren")
    mediana = cliente.TotalChildren.median()
    print(mediana)
    print("------------------------------------")
    print("Calcular la moda de TotalChildren")
    moda = cliente.TotalChildren.mode()
    print(moda)
    print("\n")
TotalChildren()